name: my-copilot build-deploy

on:
  push:
    branches: [main]
    paths:
      - 'apps/my-copilot/**'
      - '.github/workflows/my-copilot.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/my-copilot/**'
      - '.github/workflows/my-copilot.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: nais/actions/.github/workflows/mise-build-deploy-nais.yaml@f48f094a6474ff06e70df118f21f13c1ac349d37 # ratchet:nais/actions/.github/workflows/mise-build-deploy-nais.yaml@main
    with:
      working-directory: apps/my-copilot
      mise-setup-tasks: '["install"]'
      mise-tasks: '["lint", "check"]'
      deploys-to-nais: true
      nais-team: nais
      nais-clusters: '["dev-gcp", "prod-gcp"]'
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
